
name: MediConnect
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  provider: ^6.0.5
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  url_launcher: ^6.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/MediNova.png
