// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWfm6bsgkTlkFibSKbw0bRggxmZlpl2s',
    appId: '1:988901526750:web:2611b56581f3e7e36ac64f',
    messagingSenderId: '988901526750',
    projectId: 'mediconnect-a0922',
    authDomain: 'mediconnect-a0922.firebaseapp.com',
    storageBucket: 'mediconnect-a0922.firebasestorage.app',
    measurementId: 'G-P61Z3HEHXY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGWfm6bsgkTlkFibSKbw0bRggxmZlpl2s',
    appId: '1:988901526750:web:726edd8df25b6c726ac64f',
    messagingSenderId: '988901526750',
    projectId: 'mediconnect-a0922',
    authDomain: 'mediconnect-a0922.firebaseapp.com',
    storageBucket: 'mediconnect-a0922.firebasestorage.app',
    measurementId: 'G-M7PR018BMW',
  );

}